replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  name: nginx-service

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: nginx.example.com
      paths:
        - /
  tls: []
